function [sResult] = runFmincon(sProblem)
    [x, fval, exitflag, output, lambda, grad, hessian] = ...
        fmincon( ...
              sProblem.objective ...
            , sProblem.x0 ...
            , sProblem.Aineq ...
            , sProblem.bineq ...
            , sProblem.Aeq ...
            , sProblem.beq ...
            , sProblem.lb ...
            , sProblem.ub ...
            , sProblem.nonlcon ...
            , sProblem.options ...
            );
    sResult = struct( ...
          'x', x ...
        , 'fval', fval ...
        , 'exitflag', exitflag ...
        , 'output', output ...
        , 'lambda', lambda ...
        , 'grad', grad ...
        , 'hessian', hessian ...
        );
end
